version: '3.8'

services:
  backend:
    container_name: backend_tiquim
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - ./backend/.env
    restart: on-failure
    depends_on:
      - mysql

  frontend:
    container_name: frontend_tiquim
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  mysql:
    container_name: db_tiquim
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  bd_gui:
    container_name: bd_gui_tiquim
    image: phpmyadmin:latest
    ports:
      - ${BD_GUI_PORT}:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  mysql_data:
  mysql_config:
